# Site settings
title: Seonghyeon Nam, CS Ph.D. Candidate @ Yonsei University
email: shnnam@yonsei.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Seonghyeon Nam, CS Ph.D. Candidate @ Yonsei University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://snam.ml" # the base hostname & protocol for your site
facebook_username: woozzu
github_username:  woozzu
linkedin_username: seonghyeonnam

# Build settings
markdown: kramdown
