# Site settings
title: Seonghyeon Nam, CS M.S./Ph.D. Student @ Yonsei University
email: woozzu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Seonghyeon Nam, CS M.S./Ph.D. Student @ Yonsei University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
facebook_username: woozzu
github_username:  woozzu
linkedin_username: woozzu

# Build settings
markdown: kramdown
